source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Location_Example', :exclusive => true do
  pod "Location", :path => "../"
end

target 'Location_Tests', :exclusive => true do
  pod "Location", :path => "../"

  
end
